In [11]:
import pandas as pd
import numpy as np
import requests

In [4]:
df= pd.read_csv('链家二手房上海.csv')

In [5]:
df.shape

(152036, 25)

In [6]:
df.head(2)

,Architectural_Types,Built_up_area,Completion_date,Cover_area,Decoration,Equipped_with_elevators,Heating_mode,House_orientation,House_use,Housing_type,...,building_structure,floor,headline,house_location,house_price_perunit,house_price_tenK,house_website_traffic,household_ratio_perstair,sell_date,url
0,塔楼,50.21㎡,2003,50.21㎡,其他,有,NaN,暂无数据,商业办公类,1室1厅1厨1卫,...,钢混结构,低楼层(共50层),世纪时空大厦 1室1厅 50.21平米,"上海房产网,上海二手房成交,静安二手房成交,静安寺二手房成交,世纪时空大厦二手房成交",29875,150,暂无数据,两梯十六户,2011.10.26 成交,https://sh.lianjia.com/chengjiao/107010000099....
1,塔楼,50.19㎡,1998,50.19㎡,其他,有,NaN,南,普通住宅,1室0厅1厨1卫,...,钢混结构,低楼层(共38层),爱俪轩 1室0厅 50.19平米,"上海房产网,上海二手房成交,静安二手房成交,静安寺二手房成交,爱俪轩二手房成交",30883,155,暂无数据,三梯十一户,2012.07.23 成交,https://sh.lianjia.com/chengjiao/107010000934....

In [7]:
lst_loc = []
lst_loc_old = df['house_location'].tolist()
for i in range(len(lst_loc_old)):
    templst = lst_loc_old[i].split('二手房成交')[0:]
    templst = [j.replace(",", "") for j in templst][1:-1]
    templst.insert(0, "上海")
    ''.join(templst)
    lst_loc.append(' '.join(templst))

In [8]:
df['house_location'] = lst_loc

In [9]:
list_location = df['house_location'].value_counts().index.tolist()

In [14]:
dict_location = {}
My_key = 'f654d644aeae0e1da847d7ca408f4370'
url_pre = 'https://restapi.amap.com/v3/geocode/geo?key={}&address={}&city={}'
counter = 0
for i in list_location:
    location = i.split(" ")[-1]
    url = url_pre.format(My_key, location, '上海')
    res = requests.get(url).json()
    if res['status'] == '0':
        dict_location[i] = np.nan
        counter +=1
    else:
        try: 
            dict_location[i] = res['geocodes'][0]['location']
            if counter % 250 == 0:
                print('one batch(250) processed')
        except:
            dict_location[i] = np.nan
            
        counter +=1

one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed
one batch(250) processed

In [15]:
df['location_coords'] = np.nan

In [16]:
counter = 0
for i in list_location:
    counter += 1
    df_temp = df[df['house_location'] == i]
    df_temp_index = df_temp.index.tolist()
    df.iloc[df_temp_index,25] = dict_location[i]
    if counter %50 == 0:
        print('A batch(50) is done')

A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done
A batch(50) is done

In [17]:
df.head()

,Architectural_Types,Built_up_area,Completion_date,Cover_area,Decoration,Equipped_with_elevators,Heating_mode,House_orientation,House_use,Housing_type,...,floor,headline,house_location,house_price_perunit,house_price_tenK,house_website_traffic,household_ratio_perstair,sell_date,url,location_coords
0,塔楼,50.21㎡,2003,50.21㎡,其他,有,NaN,暂无数据,商业办公类,1室1厅1厨1卫,...,低楼层(共50层),世纪时空大厦 1室1厅 50.21平米,上海 静安 静安寺 世纪时空大厦,29875,150,暂无数据,两梯十六户,2011.10.26 成交,https://sh.lianjia.com/chengjiao/107010000099....,"121.442728,31.222463"
1,塔楼,50.19㎡,1998,50.19㎡,其他,有,NaN,南,普通住宅,1室0厅1厨1卫,...,低楼层(共38层),爱俪轩 1室0厅 50.19平米,上海 静安 静安寺 爱俪轩,30883,155,暂无数据,三梯十一户,2012.07.23 成交,https://sh.lianjia.com/chengjiao/107010000934....,"121.438537,31.216437"
2,板楼,51.27㎡,2012,暂无数据,其他,有,NaN,暂无数据,普通住宅,1室1厅1厨1卫,...,低楼层(共15层),东绣苑 1室1厅 51.27平米,上海 浦东 川沙 东绣苑,46421,238,暂无数据,两梯四户,2017.02.22 成交,https://sh.lianjia.com/chengjiao/107001270745....,"121.692272,31.176522"
3,塔楼,51.82㎡,2004,暂无数据,其他,有,NaN,暂无数据,普通住宅,1室1厅1厨1卫,...,低楼层(共23层),圣天地酒店式公寓 1室1厅 51.82平米,上海 普陀 长寿路 圣天地酒店式公寓,71787,372,暂无数据,五梯三十三户,2017.03.18 成交,https://sh.lianjia.com/chengjiao/107000385291....,"121.443421,31.242795"
4,板楼,51.82㎡,2014,暂无数据,精装,有,NaN,南,普通住宅,1室1厅1厨1卫,...,低楼层(共15层),金铭文博水景(公寓) 1室1厅 51.82平米,上海 闵行 颛桥 金铭文博水景(公寓),54999,285,551,两梯五户,2018.05.30 成交,https://sh.lianjia.com/chengjiao/107100222969....,"121.405227,31.066524"

In [20]:
My_key = 'f654d644aeae0e1da847d7ca408f4370'
url_pre = 'https://restapi.amap.com/v3/geocode/geo?key={}&address={}&city={}'
url = url_pre.format(My_key, '东绣苑', '上海')
res = requests.get(url).json()
print(res)

{'status': '1', 'info': 'OK', 'infocode': '10000', 'count': '1', 'geocodes': [{'formatted_address': '上海市浦东新区东绣苑', 'country': '中国', 'province': '上海市', 'citycode': '021', 'city': '上海市', 'district': '浦东新区', 'township': [], 'neighborhood': {'name': [], 'type': []}, 'building': {'name': [], 'type': []}, 'adcode': '310115', 'street': [], 'number': [], 'location': '121.692272,31.176522', 'level': '兴趣点'}]}

In [18]:
df.to_csv('上海二手房地址数据.csv', encoding = 'utf-8-sig',index = False)